// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import React from 'react';
// import Navbar from '@/components/Navbar';
// import Footer from '@/components/Footer';

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Portfolio",
//   description: "Generated by create next app",
// };


// export default function Layout({ children }: { children: React.ReactNode }) {
//   return (
//     <>
//       <Navbar />
//       {children}
//       <Footer />
//     </>
//   );
// }






// import type { Metadata } from "next";
// // import { Inter } from "next/font/google";
// import "./globals.css";
// import React from 'react';
// import Navbar from '@/components/Navbar';
// import Footer from '@/components/Footer';

// // const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Portfolio",
//   description: "Generated by create next app",
// };

// export default function Layout({ children }: { children: React.ReactNode }) {
//   return (
//     <>
//       <Navbar />
//       {children}
//       <Footer />
//     </>
//   );
// }





import type { Metadata } from "next";
import "./globals.css";
import React from 'react';
import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ErrorBoundary from '@/components/ErrorBoundary';

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

